#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
apt-get -y update
apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get -y install haproxy
echo " listen load_balancer bind *:80 mode http balance roundrobin option httpclose option forwardfor server 154462-web-01 54.175.232.61:80 check server 154462-web-02 54.237.61.178:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
